#!/bin/bash

source "$HOME/.config/sketchybar/functions.sh"

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
cd $HOME/.config/sketchybar/helper && make
$HOME/.config/sketchybar/helper/helper $HELPER > /dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

# Setting up the general bar appearance and default values
TEMPIFS="$IFS"
IFS=$'\n'
barargs=($(explode_args "bar"))
defaultargs=($(explode_args "default"))
IFS="$TEMPIFS"

eval sketchybar --bar "${barargs[@]}" --default "${defaultargs[@]}"
eval sketchybar --bar "${barargs[@]}" --default "${defaultargs[@]}"

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/upcoming.sh"

# Center
# source "$ITEM_DIR/spotify.sh"

# Right
# source "$ITEM_DIR/calendar.sh"
# source "$ITEM_DIR/brew.sh"
# source "$ITEM_DIR/github.sh"
# source "$ITEM_DIR/volume.sh"
# source "$ITEM_DIR/divider.sh"

source "$ITEM_DIR/time.sh"

source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/stats.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/vpn.sh"
source "$ITEM_DIR/weather.sh"
source "$ITEM_DIR/uptime_kuma.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
